openapi: 3.0.0
info:
  title: Brick Base
  description:  |-
    A web app to keep track of your LEGO sets and their value.
    
    All endpoints are prefixed with the base url of /api/v1
    
    Some useful links:
    - [Bricklink](https://www.bricklink.com/v2/main.page)
    - [Mongo Atlas](https://www.mongodb.com/products/platform/atlas-database)
  
  contact:
    email: lachiestewart2003@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

tags:
  - name: users
    description: Endpoints for user related actions
  - name: items
    description: Endpoints for handling user's items
  - name: backend
    description: Endpoints used during development

paths:

  /clear:
    post:
      tags:
        - backend
      summary: Removes all data from the database
      operationId: clearDatabase
      responses:
        '200':
          description: Successfully cleared data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: Internal server error

  /reset:
    post:
      tags:
        - backend
      summary: Resets the database to its initial state with the default data
      operationId: resetDatabase
      responses:
        '200':
          description: Successfully reset database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
                
        '500':
          description: Internal server error

  /user/register:
    post:
      tags:
        - users
      summary: Register a new Brick Base user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses: 
        '201':
          description: User registered successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: Internal server error

  /users:
    get:
      tags:
        - users
      summary: Get all Brick Base users
      operationId: getAllUsers
      responses:
        '200':
          description: A list of all Brick Base users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error

  /user:
    get:
      tags:
        - users
      summary: Get a Brick Base user by their email address
      operationId: getUserByEmail
      parameters:
        - name: Email Address 
          in: query
          description: Email address of the user to get
          required: true
      responses:
        '200':
          description: The Brick Base user with the given email address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: A Brick Base user doesn't exist with the given email address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '500':
          description: Internal server error
  
  /users/login:
    post:
      tags: 
        - users
      summary: Login a registered Brick Base user
      operationId: loginUser
      responses:
        ''

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          nullable: true
          format: uuid
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
        items:
          type: array
          items:
            $ref: '#/components/schemas/BricklinkItemRequest'

    BricklinkItem:
      required:
        - no
        - name
        - type
        - category_id
        - alternate_no
        - image_url
        - thumbnail_url
        - weight
        - dim_x
        - dim_y
        - dim_z
        - year_released
        - is_obsolete
      type: object
      properties:
        no:
          type: string
        name:
          type: string
        type:
          type: string
        category_id:
          type: integer
        alternate_no:
          type: string
        image_url:
          type: string
        thumbnail_url:
          type: string
        weight:
          type: string
        dim_x:
          type: string
        dim_y:
          type: string
        dim_z:
          type: string
        year_released:
          type: integer
        is_obsolete:
          type: boolean
        description:
          type: string
          nullable: true
        language_code:
          type: string
          nullable: true
    BricklinkItemRequest:
      required:
        - no
        - type
      type: object
      properties:
        no:
          type: string
        type:
          type: string
    BricklinkSuperset:
      type: object
      properties:
        color_id:
          type: integer
        entries:
          type: array
          items:
            type: object
            properties:
              item:
                $ref: '#/components/schemas/BricklinkItem'
              quantity:
                type: integer
              appears_as:
                type: string
    BricklinkSupersetRequest:
      required:
        - no
        - type
        - color_id
      type: object
      properties:
        no:
          type: string
        type:
          type: string
        color_id:
          type: integer
    BricklinkSubset:
      type: object
      properties:
        match_no:
          type: integer
        entries:
          type: array
          items:
            type: object
            properties:
              item:
                $ref: '#/components/schemas/BricklinkItem'
              color_id:
                type: integer
              quantity:
                type: integer
              extra_quantity:
                type: integer
              is_alternate:
                type: boolean
              is_counterpart:
                type: boolean
    BricklinkSubsetRequest:
      required:
        - no
        - type
        - color_id
        - box
        - instruction
        - break_minifigs
        - break_subsets
      type: object
      properties:
        no:
          type: string
        type:
          type: string
        color_id:
          type: integer
        box:
          type: boolean
        instruction:
          type: boolean
        break_minifigs:
          type: boolean
        break_subsets:
          type: boolean
    BricklinkPriceGuide:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/BricklinkItem'
        new_or_used:
          type: string
          enum:
            - N
            - U
        currency_code:
          type: string
        min_price:
          type: string
        max_price:
          type: string
        avg_price:
          type: string
        qty_avg_price:
          type: string
        unit_quantity:
          type: integer
        total_quantity:
          type: integer
        price_detail:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/BricklinkCurrentPriceDetail'
              - $ref: '#/components/schemas/BricklinkPastPriceDetail'
    BricklinkPriceDetail:
      type: object
      properties:
        quantity:
          type: integer
        unit_price:
          type: string
    BricklinkCurrentPriceDetail:
      allOf:
        - $ref: '#/components/schemas/BricklinkPriceDetail'
        - properties:
            shipping_available:
              type: boolean
    BricklinkPastPriceDetail:
      allOf:
        - $ref: '#/components/schemas/BricklinkPriceDetail'
        - properties:
            seller_country_code:
              type: string
            buyer_country_code:
              type: string
            date_ordered:
              type: string
    BricklinkKnownColor:
      type: object
      properties:
        color_id:
          type: string
        quantity:
          type: string
    BricklinkColor:
      type: object
      properties:
        color_id:
          type: integer
        color_name:
          type: string
        color_code:
          type: string
        color_type:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
          description: Message indicating the result of the operation
